"""Emit grammar/conformance.json — the contract between the Python and JS automata.

The decoder exists twice on purpose and two implementations of a grammar drift, so this
freezes a sample of the Python automaton's behaviour that the browser suite asserts
against — rerun `make conformance` whenever eval/cron_automaton.py changes, or that suite
stays green against a stale recording.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "eval"))

from cron_automaton import EOS, default_automaton, is_well_formed  # noqa: E402

OUT = ROOT / "grammar" / "conformance.json"
STATE_CASES = 2500
ACCEPT_CASES = 600


def main() -> None:
    auto = default_automaton()
    grammar = auto.grammar
    rng = random.Random(2026)

    base: list[tuple[int, str, int]] = []
    seen: set[tuple[int, str]] = set()

    # Random walk, so the sampled states are the ones decoding actually visits.
    while len(base) < STATE_CASES:
        state = auto.start()
        for _ in range(grammar.max_length + 2):
            key = (state[0], state[1])
            if key not in seen:
                seen.add(key)
                base.append(state)
                if len(base) >= STATE_CASES:
                    break
            allowed = sorted(auto.allowed(state))
            ch = rng.choice(allowed)
            if ch == EOS:
                break
            state = auto.advance(state, ch)

    # A uniform walk peters out around 50 characters, so each state is replayed at several
    # budgets — including the tightest ones, where the length gate actually lives.
    states: list[dict] = []
    for fi, text, total in base:
        for budget_total in sorted({total, *(grammar.max_length - k for k in (1, 2, 3, 5))}):
            if budget_total < total:
                continue
            allowed = auto.allowed((fi, text, budget_total))
            states.append(
                {
                    "field": fi,
                    "text": text,
                    "total": budget_total,
                    "allowed": "".join(sorted(c for c in allowed if c != EOS)),
                    "canEnd": EOS in allowed,
                    "completionLen": auto.completion_len((fi, text)),
                }
            )

    accepts: list[dict] = []
    corpus = ROOT / "data" / "out" / "canonical.jsonl"
    if corpus.exists():
        crons = [json.loads(l)["cron"] for l in corpus.read_text().splitlines() if l.strip()]
        rng.shuffle(crons)
        for cron in crons[: ACCEPT_CASES // 2]:
            accepts.append({"text": cron, "wellFormed": True})

    junk = [
        "", " ", "*", "** * * *", "60 * * * *", "0 24 * * *", "0 0 0 * *", "0 0 32 * *",
        "*/0 * * * *", "5-2 * * * *", "1,,2 * * * *", "1, * * * *", "*,5 * * * *",
        "3,3/4 * * * *", "0-59,5 * * * *", "0 0 * * 7", "a * * * *", "1  * * * *",
        "1 * * * * ", "-1 * * * *", "1/ * * * *", "0 0 31 2 *", "1-5-7 * * * *",
    ]
    while len(accepts) < ACCEPT_CASES:
        text = rng.choice(junk)
        if not is_well_formed(text, auto):
            accepts.append({"text": text, "wellFormed": False})
        rng.shuffle(junk)

    payload = {
        "comment": "Generated by grammar/generate_conformance.py. Do not edit by hand.",
        "alphabet": grammar.alphabet,
        "maxLength": grammar.max_length,
        "states": states,
        "expressions": accepts,
    }
    tight = [s_ for s_ in states if s_["total"] >= grammar.max_length - 5]
    assert all("total" in s_ for s_ in states)
    OUT.write_text(json.dumps(payload, indent=1))
    print(f"wrote {OUT}: {len(states)} state cases ({len(base)} base), {len(accepts)} expression cases")
    print(f"  {len(tight)} states sit within 5 characters of the length cap")


if __name__ == "__main__":
    main()
